### PR TITLE
fix: fixes parsing errors

### LINKED ISSUE #6: bug: parsing errors
**Describe the bug**

Parsing errors for several properties, like mass on a person.

**To Reproduce**

1. Make a request for the film with ID 3
2. Look at the great error

**Expected behavior**

Should return normal results

### PR DESCRIPTION
**Pull request by thehairy**
Fixes several parsing errors and allows episode id's to be float

fix #6

### CODE REVIEW

File: src/structures/Vehicle.ts [hunk 1]
```diff
@@ -4,7 +4,10 @@ import { Field, Float, Int, ObjectType } from 'type-graphql';
 
 @ObjectType({ description: 'A vehicle that appeared in Star Wars' })
 export default class Vehicle {
-	@Field(() => Int, { description: 'The maximum cargo capacity of this vehicle in kilograms' })
+	@Field(() => Int, {
+		nullable: true,
+		description: 'The maximum cargo capacity of this vehicle in kilograms'
+	})
 	public cargoCapacity!: number;
```
Comment (Favna) [inline src/structures/Vehicle.ts:11]:
```suggestion
	public cargoCapacity?: number | null;
```

**Review by Favna — CHANGES_REQUESTED** [review]

**Review by Favna — APPROVED** [review]

**Comment by Favna** [comment]
@all-contributors please add @thehairy for code and bug
